micronaut:
  application:
    name: micronaut-liquibase-example
---
# Persistence
hibernate:
  hbm2ddl:
    auto: 'update'
  show_sql: false
dataSource:
  url: 'jdbc:h2:file:./devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE'
  username: 'sa'
  password: ''
  driverClassName: 'org.h2.Driver'
  dialect: 'H2'
  schemaGenerate: 'CREATE-DROP'
---
